apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsapp-az
  labels:
    app: myinsapp-az
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myinsapp-az
  template:
    metadata:
      labels:
        app: myinsapp-az
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: myinsapp-deployment-az
        image: myinsapp.azurecr.io/myinsapp:v1
        ports:
        - name: http
          containerPort: 5000